[package]
name = "gl45"
version = "0.0.1"
authors = ["Adam Kidder <thekidder@gmail.com>"]
build = "build.rs"

[lib]
name = "gl45"

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dependencies]
gl_common = "*"
libc = "*"